/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicPackage;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author andre
 */
public class AdminMainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminMainFrame
     */
    public AdminMainFrame() {
        initComponents();
        showDate();
        showTime();

        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Admin.png")));

        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(lblSecretary.getWidth(), lblSecretary.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);

        lblSecretary.setIcon(i);

    }
    // Show Current System Date
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("E, dd MMMM yyyy");
        String date = new SimpleDateFormat("yyyy-MM-dd",   Locale.getDefault()).format(new Date());
        lblDate.setText(s.format(d));
       
    }
    // Show Current System Time
    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a zzzz");
                lblTime.setText(s.format(d));
            }

        }
        ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        lblSecretary = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        btnRestore = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnRestore1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(734, 532));

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        upperPanel.setBackground(new java.awt.Color(245, 198, 165));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/C.A.R.E.S._Logo(resized).png"))); // NOI18N

        lblDate.setBackground(new java.awt.Color(61, 86, 178));
        lblDate.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 78, 203));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 609, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(upperPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(upperPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 110));

        sidePanel.setBackground(new java.awt.Color(254, 241, 230));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(lblSecretary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 70));

        jLabel2.setBackground(new java.awt.Color(61, 86, 178));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 86, 178));
        jLabel2.setText("Admin");
        sidePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        btnAddUser.setBackground(new java.awt.Color(254, 241, 230));
        btnAddUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(61, 86, 178));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/216487_add_user_icon.png"))); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.setToolTipText("");
        btnAddUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddUser.setBorderPainted(false);
        btnAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddUser.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAddUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddUser.setIconTextGap(45);
        btnAddUser.setOpaque(false);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });
        sidePanel.add(btnAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 50));

        btnBackup.setBackground(new java.awt.Color(254, 241, 230));
        btnBackup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBackup.setForeground(new java.awt.Color(61, 86, 178));
        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/iconfinder_50_Cloud_Arrow_Up_183360.png"))); // NOI18N
        btnBackup.setText("Back-up");
        btnBackup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBackup.setBorderPainted(false);
        btnBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackup.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBackup.setIconTextGap(45);
        btnBackup.setOpaque(false);
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        sidePanel.add(btnBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 210, 50));

        btnRestore.setBackground(new java.awt.Color(254, 241, 230));
        btnRestore.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRestore.setForeground(new java.awt.Color(61, 86, 178));
        btnRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/2561458_list_icon.png"))); // NOI18N
        btnRestore.setText("User List");
        btnRestore.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRestore.setBorderPainted(false);
        btnRestore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestore.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRestore.setIconTextGap(45);
        btnRestore.setOpaque(false);
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });
        sidePanel.add(btnRestore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 50));

        btnExit.setBackground(new java.awt.Color(254, 241, 230));
        btnExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(61, 86, 178));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/iconfinder_glyph-20_3403739.png"))); // NOI18N
        btnExit.setText("Log-Out");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        sidePanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 210, 50));

        btnRestore1.setBackground(new java.awt.Color(254, 241, 230));
        btnRestore1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRestore1.setForeground(new java.awt.Color(61, 86, 178));
        btnRestore1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/3669259_ic_restore_icon.png"))); // NOI18N
        btnRestore1.setText("Restore Data");
        btnRestore1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRestore1.setBorderPainted(false);
        btnRestore1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestore1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRestore1.setIconTextGap(30);
        btnRestore1.setOpaque(false);
        btnRestore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestore1ActionPerformed(evt);
            }
        });
        sidePanel.add(btnRestore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 210, 50));

        MainPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 210, 560));

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(61, 86, 178));
        jLabel3.setText("Time:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 50, -1));

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lblTime.setForeground(new java.awt.Color(61, 86, 178));
        lblTime.setText(" ");
        lblTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 260, 60));

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1090, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int msg = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out of account?");
        if (msg == 0) {
            new LogInPageforClinic().setVisible(true);
            this.setVisible(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoreActionPerformed
        JOptionPane.showMessageDialog(null, "Feature currently unavailable");     // TODO add your handling code here:
    }//GEN-LAST:event_btnRestoreActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed

        JOptionPane.showMessageDialog(null, "Feature currently unavailable");
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        new AddUser().setVisible(true);

    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnRestore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestore1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRestore;
    private javax.swing.JButton btnRestore1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSecretary;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

    private static class javaGUI {

        public javaGUI() {

        }
    }
}
