/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicPackage;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author andre
 */
public class internalFrameAppoint extends javax.swing.JInternalFrame {

    /**
     * Creates new form internalFrameAppoint
     */
    public internalFrameAppoint() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSDateChooserBeanInfo1 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        rSFotoCircleBeanInfo1 = new rojerusan.RSFotoCircleBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSetAppoint = new necesario.MaterialButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojerusan.RSTableMetro();
        rSButtonIconD1 = new rojerusan.RSButtonIconD();
        jLabel3 = new javax.swing.JLabel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        rSComboMetro1 = new rojerusan.RSComboMetro();

        setPreferredSize(new java.awt.Dimension(1070, 620));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1070, 620));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 620));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Appointments");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        btnSetAppoint.setBackground(new java.awt.Color(0, 112, 192));
        btnSetAppoint.setForeground(new java.awt.Color(255, 255, 255));
        btnSetAppoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/2639799_create_new_icon.png"))); // NOI18N
        btnSetAppoint.setText("Set an Appointment");
        btnSetAppoint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetAppoint.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        btnSetAppoint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetAppointMouseClicked(evt);
            }
        });
        jPanel1.add(btnSetAppoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 240, 80));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PATIENT ID: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rSTableMetro1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(rSTableMetro1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1020, 250));

        rSButtonIconD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/254211_search_view_zoom_icon.png"))); // NOI18N
        rSButtonIconD1.setText("Search");
        jPanel1.add(rSButtonIconD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Time:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, 20));

        jCTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jCTextField1.setPlaceholder("Enter Patient ID...");
        jPanel1.add(jCTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 230, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of Appointment:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        jPanel1.add(rSComboMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetAppointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetAppointMouseClicked
        int msg = JOptionPane.showConfirmDialog(null, "Save Appointment?");

        if (msg==0)
        {
            JOptionPane.showMessageDialog(this, "Appointment Saved!");
        } else if (msg == 1)
        {
           JOptionPane.showMessageDialog(this, "Appointment Cancelled");
        }


    }//GEN-LAST:event_btnSetAppointMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.MaterialButton btnSetAppoint;
    private app.bolivia.swing.JCTextField jCTextField1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonIconD rSButtonIconD1;
    private rojerusan.RSComboMetro rSComboMetro1;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo1;
    private rojerusan.RSFotoCircleBeanInfo rSFotoCircleBeanInfo1;
    private rojerusan.RSTableMetro rSTableMetro1;
    // End of variables declaration//GEN-END:variables
}
