/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicPackage;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;
//import java.sql.*;

/**
 *
 * @author andre
 */
public class InternalFrameAddUser extends javax.swing.JInternalFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;

    /**
     * Creates new form InternalFramePatientRec
     */
    public InternalFrameAddUser() {
        initComponents();
        InternalFrameBorder();
        autoID();
        //  GenerateID();
        /*   this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
            ui.setNorthPane(null);
            pack();
         */
    }

    // This method removes the border of the InternalFrame
    void InternalFrameBorder() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        pack();
    }

    // Function to auto generate ID for user
    /*  public void GenerateID() {

       try {
            Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("select MAX(userID) from sales");
           rs.next();

    /       rs.getString("MAX(userID)");

            if (rs.getString("MAX(userID)") == null) {
               userIDLabel.setText("CCS-0001");

            } else {
    /          long id = Long.parseLong(rs.getString("MAX(userID)").substring(2, rs.getString("MAX(userID)").length()));
                id++;
              userIDLabel.setText("CCS-" + String.format("%03", id));
           }
        } catch (SQLException ex) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, ex);
      }

    } */
    public void autoID() {
        try {
            DatabaseConnection connection = new DatabaseConnection();
            con = connection.getConnection();
            String query = "select max(user_ID) from user_info";

            st = con.createStatement();
            rs = st.executeQuery(query);
            rs.next();

            rs.getString("max(user_ID)");

            if (rs.getString("max(user_ID)") == null) {
                userIDLabel.setText("CS001");
            } else {
                Long id = Long.parseLong(rs.getString("max(user_ID)").substring(2, rs.getString("max(user_ID)").length()));
                id++;
                userIDLabel.setText("CS" + String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(InternalFrameAddUser.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
            } catch (Exception e) {
                /* Ignored */ }
            try {
                pst.close();
            } catch (Exception e) {
                /* Ignored */ }
            try {
                con.close();
            } catch (Exception e) {
                /* Ignored */ }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtlastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        textAge = new javax.swing.JTextField();
        birthDate = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        comboRole = new rojerusan.RSComboMetro();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel14 = new javax.swing.JPanel();
        clearButton = new rojerusan.RSMaterialButtonCircle();
        btnAddRec = new rojerusan.RSMaterialButtonCircle();

        setPreferredSize(new java.awt.Dimension(1070, 620));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1060, 620));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 86, 178));
        jLabel1.setText("ADD NEW USER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        btnBack.setFont(new java.awt.Font("Gadugi", 1, 11)); // NOI18N
        btnBack.setText("X");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 50, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 133, 187));
        jLabel2.setText("Birthdate:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtlastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtlastName.setOpaque(false);
        txtlastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlastNameKeyTyped(evt);
            }
        });
        jPanel6.add(txtlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 133, 187));
        jLabel3.setText("First Name");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        txtfirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtfirstName.setOpaque(false);
        txtfirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirstNameKeyTyped(evt);
            }
        });
        jPanel6.add(txtfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 220, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 133, 187));
        jLabel4.setText("Username");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtUserName.setOpaque(false);
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        jPanel6.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 220, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 133, 187));
        jLabel5.setText("Last Name");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("*from date of Birth");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 133, 187));
        jLabel7.setText("Role:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 133, 187));
        jLabel8.setText("Address:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtAddress.setOpaque(false);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        jPanel6.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 840, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 133, 187));
        jLabel9.setText("Age");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 133, 187));
        jLabel10.setText("Contact Number:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        txtContactNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtContactNo.setOpaque(false);
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });
        jPanel6.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 220, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 133, 187));
        jLabel11.setText("User ID:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        userIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userIDLabel.setForeground(new java.awt.Color(0, 51, 204));
        userIDLabel.setText("CS001");
        jPanel6.add(userIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 133, 187));
        jLabel12.setText("Password:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtPassword.setOpaque(false);
        jPanel6.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 350, 40));

        textAge.setEditable(false);
        textAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textAge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        textAge.setEnabled(false);
        textAge.setOpaque(false);
        jPanel6.add(textAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 40, 30));

        birthDate.setDateFormatString("dd/MM/yyyy");
        birthDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                birthDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        birthDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthDateMouseClicked(evt);
            }
        });
        birthDate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                birthDateInputMethodTextChanged(evt);
            }
        });
        birthDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                birthDatePropertyChange(evt);
            }
        });
        jPanel6.add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 30));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(38, 133, 187));
        jLabel13.setText("Confirm Password:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        txtConfirmPassword.setOpaque(false);
        jPanel6.add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 370, 40));

        comboRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secretary", "Admin" }));
        comboRole.setColorArrow(new java.awt.Color(38, 133, 187));
        comboRole.setColorBorde(new java.awt.Color(38, 133, 187));
        comboRole.setColorFondo(new java.awt.Color(38, 133, 187));
        comboRole.setDoubleBuffered(true);
        comboRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel6.add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 210, -1));

        rSMaterialButtonRectangle1.setText("Get Age");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel6.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 100, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 970, 420));

        jPanel14.setBackground(new java.awt.Color(255, 179, 68));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 720, 3));

        clearButton.setBackground(new java.awt.Color(255, 0, 51));
        clearButton.setBorder(null);
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/103765_close_user_settings_icon (1).png"))); // NOI18N
        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 150, 70));

        btnAddRec.setBackground(new java.awt.Color(0, 166, 89));
        btnAddRec.setBorder(null);
        btnAddRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/103765_close_user_settings_icon (1).png"))); // NOI18N
        btnAddRec.setText("Register");
        btnAddRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void birthDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_birthDateAncestorAdded

    }//GEN-LAST:event_birthDateAncestorAdded

    private void birthDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthDateMouseClicked

    }//GEN-LAST:event_birthDateMouseClicked

    private void birthDateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_birthDateInputMethodTextChanged

    }//GEN-LAST:event_birthDateInputMethodTextChanged

    private void birthDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_birthDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDatePropertyChange

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // Takes the string value of the jDateChooser
        String dateofBirth = ((JTextField) birthDate.getDateEditor().getUiComponent()).getText();

        //Splits the date into an array
        String dob[] = dateofBirth.split("/");

        // Elements in the declared array
        int day = Integer.parseInt(dob[0]);
        int month = Integer.parseInt(dob[1]);
        int year = Integer.parseInt(dob[2]);

        // Storing the localdates
        LocalDate selectedDate = LocalDate.of(year, month, day);
        LocalDate currentDate = LocalDate.now();

        // Validating to rewrite textfield if not empty
        if (textAge.getText() != "") {
            textAge.setText("");
            //Outputting the date
            int ResultYear = Period.between(selectedDate, currentDate).getYears();
            textAge.setText("" + ResultYear);
        } else if (textAge.getText() == "") {
            textAge.setText("");
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
      char c = evt.getKeyChar();

      if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || c== KeyEvent.VK_DELETE)){

          evt.consume();
    }
    }//GEN-LAST:event_txtContactNoKeyTyped

    private void txtlastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastNameKeyTyped
        char c = evt.getKeyChar();

        if(!(Character.isAlphabetic(c) || c== KeyEvent.VK_SPACE || c==KeyEvent.VK_DELETE)){

            evt.consume();
        }
    }//GEN-LAST:event_txtlastNameKeyTyped

    private void txtfirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstNameKeyTyped
     char c = evt.getKeyChar();

        if(!(Character.isAlphabetic(c) || c== KeyEvent.VK_SPACE || c==KeyEvent.VK_DELETE)){

            evt.consume();
        }
    }//GEN-LAST:event_txtfirstNameKeyTyped

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
       char c = evt.getKeyChar();

        if(!(Character.isAlphabetic(c) || c== KeyEvent.VK_SPACE || c==KeyEvent.VK_DELETE)){

            evt.consume();
        }
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
     char c = evt.getKeyChar();

        if(!(Character.isAlphabetic(c) || c== KeyEvent.VK_SPACE || c==KeyEvent.VK_DELETE)){

            evt.consume();
        }
    }//GEN-LAST:event_txtAddressKeyTyped

    private void btnAddRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecActionPerformed
        Connection con;

        //Password
        String password = new String(txtPassword.getPassword());
        String confirmpassword = new String(txtConfirmPassword.getPassword());
        //End Password
        DatabaseConnection connection = new DatabaseConnection();
        con = connection.getConnection();
        String query = "insert into user_info(user_id, last_name, first_name, username, birth_date, age, contact_number, role, address, password) values (?,?,?,?,?,?,?,?,?,?)";
        int msg = JOptionPane.showConfirmDialog(this, "Save the record?");

        if (msg == JOptionPane.YES_OPTION) {
            try {

                 if (txtlastName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (txtfirstName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (txtUserName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (this.birthDate.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Enter a date");
                    return;
                }
                if (textAge.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (txtContactNo.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (txtAddress.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (txtPassword.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (txtConfirmPassword.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, userIDLabel.getText());
                pstmt.setString(2, txtlastName.getText());
                pstmt.setString(3, txtfirstName.getText());
                pstmt.setString(4, txtUserName.getText());
                // date
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                String d = sdf.format(birthDate.getDate());
                pstmt.setString(5, d);
                // date
                pstmt.setString(6, textAge.getText());
                pstmt.setString(7, txtContactNo.getText());
                pstmt.setString(8, comboRole.getSelectedItem().toString());
                pstmt.setString(9, txtAddress.getText());
                pstmt.setString(10, txtPassword.getText());

                //    int success = pstmt.executeUpdate();
                if (password.equals(confirmpassword)) {
                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Saved!");

//                     Clearing the textfields after saving the record
                    txtlastName.setText("");
                    txtfirstName.setText("");
                    birthDate.setCalendar(null);
                    txtUserName.setText("");
                    textAge.setText("");
                    txtContactNo.setText("");
                    txtAddress.setText("");
                    txtPassword.setText("");
                    txtConfirmPassword.setText("");


                    autoID();
                } else {
                    JOptionPane.showMessageDialog(this, "Passwords do not match. Double check your password", "User not registered", JOptionPane.WARNING_MESSAGE);
                }

//                if (success == 1) {
//                    JOptionPane.showMessageDialog(this, "Record Saved!");
//
//
//                    txtlastName.setText("");
//                    txtfirstName.setText("");
//                    birthDate.setCalendar(null);
//                    txtUserName.setText("");
//                    textAge.setText("");
//                    txtContactNo.setText("");
//                    txtAddress.setText("");
//                    txtPassword.setText("");
//
//                    autoID();
            } catch (SQLException ex) {
                Logger.getLogger(InternalFramePatientRec.class.getName()).log(Level.SEVERE, null, ex);

                // closing the connection
            } finally {
                try {
                    rs.close();
                } catch (Exception e) {
                    /* Ignored */ }
                try {
                    pst.close();
                } catch (Exception e) {
                    /* Ignored */ }
                try {
                    con.close();
                } catch (Exception e) {
                    /* Ignored */ }
            }

        }
    }//GEN-LAST:event_btnAddRecActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        txtlastName.setText("");
        txtfirstName.setText("");
        birthDate.setCalendar(null);
        txtUserName.setText("");
        textAge.setText("");
        txtContactNo.setText("");
        txtAddress.setText("");
        txtPassword.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthDate;
    private rojerusan.RSMaterialButtonCircle btnAddRec;
    private javax.swing.JButton btnBack;
    private rojerusan.RSMaterialButtonCircle clearButton;
    private rojerusan.RSComboMetro comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtlastName;
    private javax.swing.JLabel userIDLabel;
    // End of variables declaration//GEN-END:variables
}
