/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicPackage;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import net.proteanit.sql.DbUtils;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;

/**
 *
 * @author andre
 */
public class InternalFramePatientRec extends javax.swing.JInternalFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;

    /**
     * Creates new form InternalFramePatientRec
     */
    public InternalFramePatientRec() {
        initComponents();
        InternalFrameBorder();
        autoID();
        showDate();
        //getlastID();
        /*   this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
            ui.setNorthPane(null);
            pack();
         */
    }

    public void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEE, dd MMM, yyyy");
        lblDate.setText(s.format(d));
    }

    public void getlastID() {
        try {
            int lastid;
            DatabaseConnection connection = new DatabaseConnection();
            con = connection.getConnection();
            String query = "select max(patient_ID) from patient_info";
            st = con.createStatement();
            rs = st.executeQuery(query);
            if (rs.next()) {
                lastid = rs.getInt(1);
                lastid++;
                label_patientID.setText(Integer.toString(lastid));
            }
        } catch (SQLException ex) {
            Logger.getLogger(InternalFramePatientRec.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                rs.close();
            } catch (Exception e) {
                /* Ignored */ }
            try {
                pst.close();
            } catch (Exception e) {
                /* Ignored */ }
            try {
                con.close();
            } catch (Exception e) {
                /* Ignored */ }
        }

    }

    //a method that auto generates the patient ID
    public void autoID() {
        try {
            DatabaseConnection connection = new DatabaseConnection();
            con = connection.getConnection();
            String query = "select max(patient_ID) from patient_info";

            st = con.createStatement();
            rs = st.executeQuery(query);
            rs.next();

            rs.getString("max(patient_ID)");

            if (rs.getString("max(patient_ID)") == null) {
                label_patientID.setText("P0001");
            } else {
                Long id = Long.parseLong(rs.getString("max(patient_ID)").substring(2, rs.getString("max(patient_ID)").length()));
                id++;
                label_patientID.setText("P" + String.format("%04d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(InternalFrameAddUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // This method removes the border of the InternalFrame
    void InternalFrameBorder() {
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddRec = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textPhoneNo = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        birthDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaRemarks = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textFatherLName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textFatherFName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textFatherNumber = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        textFatherAge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        textMotherLName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textMotherFName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textMotherNumber = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textMotherAge = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textAge = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        label_patientID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaPrescription = new javax.swing.JTextArea();
        comboGender = new rojerusan.RSComboMetro();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        lblDate = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(38, 133, 187));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 133, 187), 2));
        setPreferredSize(new java.awt.Dimension(1070, 618));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1070, 623));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 86, 178));
        jLabel1.setText("ADD NEW PATIENT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        btnAddRec.setBackground(new java.awt.Color(0, 166, 89));
        btnAddRec.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAddRec.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/3336950_download_save_icon.png"))); // NOI18N
        btnAddRec.setText("Save");
        btnAddRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 130, 50));

        btnCancel.setBackground(new java.awt.Color(255, 0, 51));
        btnCancel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClinicPackage/images/330399_bad_cancel_clear_close_decline_icon.png"))); // NOI18N
        btnCancel.setText("Clear");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 130, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(61, 86, 178));
        jLabel8.setText("Patient ID:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        textLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(38, 133, 187)));
        textLastName.setOpaque(false);
        textLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textLastNameKeyPressed(evt);
            }
        });
        jPanel3.add(textLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 350, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 133, 187));
        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 133, 187));
        jLabel4.setText("First Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        textFirstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        textFirstName.setOpaque(false);
        textFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFirstNameKeyPressed(evt);
            }
        });
        jPanel3.add(textFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 85, 400, 40));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 133, 187));
        jLabel9.setText("Phone Number");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 120, 20));

        textPhoneNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        textPhoneNo.setOpaque(false);
        textPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPhoneNoKeyTyped(evt);
            }
        });
        jPanel3.add(textPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 240, 25));

        textAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        textAddress.setOpaque(false);
        textAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAddressKeyPressed(evt);
            }
        });
        jPanel3.add(textAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 770, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 133, 187));
        jLabel5.setText("Address");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 133, 187));
        jLabel7.setText("Date of Birth");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        birthDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(38, 133, 187)));
        birthDate.setDateFormatString("dd/MM/yyyy");
        birthDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        birthDate.setOpaque(false);
        birthDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                birthDateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        birthDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthDateMouseClicked(evt);
            }
        });
        birthDate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                birthDateInputMethodTextChanged(evt);
            }
        });
        birthDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                birthDatePropertyChange(evt);
            }
        });
        jPanel3.add(birthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(61, 86, 178));
        jLabel11.setText("Gender:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, 20));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 133, 187));
        jLabel6.setText("Remarks:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        textAreaRemarks.setColumns(20);
        textAreaRemarks.setRows(5);
        textAreaRemarks.setBorder(null);
        textAreaRemarks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textAreaRemarks.setOpaque(false);
        textAreaRemarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAreaRemarksKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(textAreaRemarks);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 500, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 204, 255)));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(38, 133, 187));
        jLabel13.setText("Last Name:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        textFatherLName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textFatherLName.setOpaque(false);
        textFatherLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFatherLNameKeyPressed(evt);
            }
        });
        jPanel4.add(textFatherLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(38, 133, 187));
        jLabel14.setText("First Name:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 30));

        textFatherFName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textFatherFName.setOpaque(false);
        textFatherFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFatherFNameKeyPressed(evt);
            }
        });
        jPanel4.add(textFatherFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 160, 30));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(38, 133, 187));
        jLabel15.setText("Phone Number:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        textFatherNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textFatherNumber.setOpaque(false);
        textFatherNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFatherNumberKeyTyped(evt);
            }
        });
        jPanel4.add(textFatherNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 230, 30));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(38, 133, 187));
        jLabel22.setText("Age:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        textFatherAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textFatherAge.setOpaque(false);
        textFatherAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFatherAgeKeyTyped(evt);
            }
        });
        jPanel4.add(textFatherAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(38, 133, 187));
        jLabel24.setText("Father's Information");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 500, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 255)));
        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(38, 133, 187));
        jLabel17.setText("Last Name:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        textMotherLName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textMotherLName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textMotherLName.setOpaque(false);
        textMotherLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMotherLNameKeyPressed(evt);
            }
        });
        jPanel5.add(textMotherLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 130, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(38, 133, 187));
        jLabel18.setText("First Name:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 30));

        textMotherFName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textMotherFName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textMotherFName.setOpaque(false);
        textMotherFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMotherFNameKeyPressed(evt);
            }
        });
        jPanel5.add(textMotherFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 160, 30));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(38, 133, 187));
        jLabel19.setText("Phone Number:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 78, 120, 20));

        textMotherNumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textMotherNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textMotherNumber.setOpaque(false);
        textMotherNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMotherNumberKeyTyped(evt);
            }
        });
        jPanel5.add(textMotherNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 240, 30));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(38, 133, 187));
        jLabel21.setText("Age:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 30));

        textMotherAge.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textMotherAge.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(38, 133, 187)));
        textMotherAge.setOpaque(false);
        textMotherAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMotherAgeKeyTyped(evt);
            }
        });
        jPanel5.add(textMotherAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(38, 133, 187));
        jLabel23.setText("Mother's Information");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 500, 120));

        textAge.setEditable(false);
        textAge.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        textAge.setForeground(new java.awt.Color(38, 133, 187));
        textAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textAge.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(38, 133, 187)));
        textAge.setEnabled(false);
        textAge.setOpaque(false);
        jPanel3.add(textAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 50, 25));

        jLabel16.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("*from date of Birth");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(38, 133, 187));
        jLabel20.setText("Age");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        label_patientID.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        label_patientID.setForeground(new java.awt.Color(0, 255, 0));
        label_patientID.setText("3");
        jPanel3.add(label_patientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 133, 187));
        jLabel10.setText("Prescription:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        textAreaPrescription.setColumns(20);
        textAreaPrescription.setRows(5);
        textAreaPrescription.setBorder(null);
        textAreaPrescription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textAreaPrescription.setOpaque(false);
        jScrollPane2.setViewportView(textAreaPrescription);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 500, 80));

        comboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        comboGender.setColorArrow(new java.awt.Color(38, 133, 187));
        comboGender.setColorBorde(new java.awt.Color(38, 133, 187));
        comboGender.setColorFondo(new java.awt.Color(38, 133, 187));
        comboGender.setDoubleBuffered(true);
        comboGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 82, 140, 40));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(38, 133, 187));
        rSMaterialButtonRectangle1.setText("Get Age");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 100, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1030, 500));

        lblDate.setBackground(new java.awt.Color(61, 86, 178));
        lblDate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 240, 40));

        jPanel14.setBackground(new java.awt.Color(255, 179, 68));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 620, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int msg = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove all fields?", "Remove Fields", JOptionPane.WARNING_MESSAGE);

        if (msg == 0) {
            // textIDNo.setText("");
            textLastName.setText("");
            textFirstName.setText("");
            birthDate.setCalendar(null);
            textAge.setText("");
            textPhoneNo.setText("");
            textAddress.setText("");
            textMotherLName.setText("");
            textMotherFName.setText("");
            textMotherAge.setText("");
            textMotherNumber.setText("");
            textFatherLName.setText("");
            textFatherFName.setText("");
            textFatherAge.setText("");
            textFatherNumber.setText("");
            textAreaRemarks.setText("");
            textAreaPrescription.setText("");
        }

    }//GEN-LAST:event_btnCancelActionPerformed

    private void birthDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthDateMouseClicked


    }//GEN-LAST:event_birthDateMouseClicked

    private void birthDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_birthDateAncestorAdded

    }//GEN-LAST:event_birthDateAncestorAdded

    private void birthDateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_birthDateInputMethodTextChanged

    }//GEN-LAST:event_birthDateInputMethodTextChanged

    private void birthDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_birthDatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_birthDatePropertyChange

    private void btnAddRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecActionPerformed
        Connection con;

        DatabaseConnection connection = new DatabaseConnection();
        con = connection.getConnection();
        String query = "insert into patient_info(patient_id, patient_lastname, patient_firstname, patient_gender, patient_DOB, patient_age, patient_contactno, patient_address, mother_lastname, mother_firstname, mother_age, mother_contactno, father_lastname, father_firstname, father_age, father_contactno, remarks, prescription, date_added) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        int msg = JOptionPane.showConfirmDialog(this, "Save the record?");

        //GET CURRENT DATE
        Date date = new Date();
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());

        if (msg == JOptionPane.YES_OPTION) {
            try {

                if (textLastName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textFirstName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textAddress.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (this.birthDate.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "Please enter a date");
                    return;
                }
                if (textAge.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textPhoneNo.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textMotherAge.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textMotherFName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textMotherLName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textMotherNumber.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textFatherAge.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textFatherLName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textFatherFName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textFatherNumber.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textAreaRemarks.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }
                if (textAreaPrescription.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all the fields");
                    return;
                }

                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, label_patientID.getText());
                pstmt.setString(2, textLastName.getText());
                pstmt.setString(3, textFirstName.getText());
                pstmt.setString(4, comboGender.getSelectedItem().toString());
                //date conversion
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                String d = sdf.format(birthDate.getDate());
                pstmt.setString(5, d);
                //end of date conversion
                pstmt.setString(6, textAge.getText());
                pstmt.setString(7, textPhoneNo.getText());
                pstmt.setString(8, textAddress.getText());
                pstmt.setString(9, textMotherLName.getText());
                pstmt.setString(10, textMotherFName.getText());
                pstmt.setString(11, textMotherAge.getText());
                pstmt.setString(12, textMotherNumber.getText());
                pstmt.setString(13, textFatherLName.getText());
                pstmt.setString(14, textFatherFName.getText());
                pstmt.setString(15, textFatherAge.getText());
                pstmt.setString(16, textFatherNumber.getText());
                pstmt.setString(17, textAreaRemarks.getText());
                pstmt.setString(18, textAreaPrescription.getText());
                // DATE ADDED
                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                String d1 = sdf1.format(sqlDate);
                pstmt.setString(19, d1);

                int success = pstmt.executeUpdate();

                if (success == 1) {
                    JOptionPane.showMessageDialog(this, "Record Saved!");

//                     Clearing the textfields after saving the record
                    textLastName.setText("");
                    textFirstName.setText("");
                    birthDate.setCalendar(null);
                    textAge.setText("");
                    textPhoneNo.setText("");
                    textAddress.setText("");
                    textMotherLName.setText("");
                    textMotherFName.setText("");
                    textMotherAge.setText("");
                    textMotherNumber.setText("");
                    textFatherLName.setText("");
                    textFatherFName.setText("");
                    textFatherAge.setText("");
                    textFatherNumber.setText("");
                    textAreaRemarks.setText("");
                    textAreaPrescription.setText("");
                    autoID();
                }

            } catch (SQLException ex) {
                Logger.getLogger(InternalFramePatientRec.class.getName()).log(Level.SEVERE, null, ex);

                // closing the connection
            } finally {
                try {
                    rs.close();
                } catch (Exception e) {
                    /* Ignored */ }
                try {
                    pst.close();
                } catch (Exception e) {
                    /* Ignored */ }
                try {
                    con.close();
                } catch (Exception e) {
                    /* Ignored */ }
            }

        }
    }//GEN-LAST:event_btnAddRecActionPerformed

    private void textPhoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPhoneNoKeyTyped
        // input validation that only accepts integer input
        char c = evt.getKeyChar();

        int length = textPhoneNo.getText().length();

        if (!Character.isDigit(c)) {
            //getToolkit().beep();
            evt.consume();
            if (c == KeyEvent.VK_DELETE) {
                evt.consume();
            } else if (c == KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            } else {
                JOptionPane.showMessageDialog(this, "You can only input numbers in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_textPhoneNoKeyTyped

    private void textMotherAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMotherAgeKeyTyped
        // input validation that only accepts integer input
        char c = evt.getKeyChar();

        int length = textMotherAge.getText().length();

        if (!Character.isDigit(c)) {
            //getToolkit().beep();
            evt.consume();
            if (c == KeyEvent.VK_DELETE) {
                evt.consume();
            } else if (c == KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            } else {
                JOptionPane.showMessageDialog(this, "You can only input numbers in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_textMotherAgeKeyTyped

    private void textMotherNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMotherNumberKeyTyped
        // input validation that only accepts integer input
        char c = evt.getKeyChar();

        int length = textPhoneNo.getText().length();

        if (!Character.isDigit(c)) {
            //getToolkit().beep();
            evt.consume();
            if (c == KeyEvent.VK_DELETE) {
                evt.consume();
            } else if (c == KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            } else {
                JOptionPane.showMessageDialog(this, "You can only input numbers in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_textMotherNumberKeyTyped

    private void textFatherAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFatherAgeKeyTyped
        // input validation that only accepts integer input
        char c = evt.getKeyChar();

        int length = textPhoneNo.getText().length();

        if (!Character.isDigit(c)) {
            //getToolkit().beep();
            evt.consume();
            if (c == KeyEvent.VK_DELETE) {
                evt.consume();
            } else if (c == KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            } else {
                JOptionPane.showMessageDialog(this, "You can only input numbers in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_textFatherAgeKeyTyped

    private void textFatherNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFatherNumberKeyTyped
        // input validation that only accepts integer input
        char c = evt.getKeyChar();

        int length = textPhoneNo.getText().length();

        if (!Character.isDigit(c)) {
            //getToolkit().beep();
            evt.consume();
            if (c == KeyEvent.VK_DELETE) {
                evt.consume();
            } else if (c == KeyEvent.VK_BACK_SPACE) {
                evt.consume();
            } else {
                JOptionPane.showMessageDialog(this, "You can only input numbers in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_textFatherNumberKeyTyped

    private void textLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textLastNameKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textLastName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textLastName.setText("");
            textLastName.setEditable(false);
        }

    }//GEN-LAST:event_textLastNameKeyPressed

    private void textFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFirstNameKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textFirstName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textFirstName.setText("");
            textFirstName.setEditable(false);
        }
    }//GEN-LAST:event_textFirstNameKeyPressed

    private void textAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAddressKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textAddress.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textAddress.setText("");
            textAddress.setEditable(false);
        }
    }//GEN-LAST:event_textAddressKeyPressed

    private void textMotherLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMotherLNameKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textMotherLName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textMotherLName.setText("");
            textMotherLName.setEditable(false);
        }
    }//GEN-LAST:event_textMotherLNameKeyPressed

    private void textMotherFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMotherFNameKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textMotherFName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textMotherFName.setText("");
            textMotherFName.setEditable(false);
        }
    }//GEN-LAST:event_textMotherFNameKeyPressed

    private void textFatherLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFatherLNameKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textFatherLName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textFatherLName.setText("");
            textFatherLName.setEditable(false);
        }
    }//GEN-LAST:event_textFatherLNameKeyPressed

    private void textFatherFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFatherFNameKeyPressed
        // CODE TO ACCCEPT ONLY ALPHABETS IN THE TEXTFIELDS
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            textFatherFName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            textFatherFName.setText("");
            textFatherFName.setEditable(false);
            //    JOptionPane.showMessageDialog(this, "Numbers are not allowed in this field", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_textFatherFNameKeyPressed

    private void textAreaRemarksKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaRemarksKeyPressed

    }//GEN-LAST:event_textAreaRemarksKeyPressed

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // Takes the string value of the jDateChooser
        String dateofBirth = ((JTextField) birthDate.getDateEditor().getUiComponent()).getText();

        //Splits the date into an array
        String dob[] = dateofBirth.split("/");

        // Elements in the declared array
        int day = Integer.parseInt(dob[0]);
        int month = Integer.parseInt(dob[1]);
        int year = Integer.parseInt(dob[2]);

        // Storing the localdates
        LocalDate selectedDate = LocalDate.of(year, month, day);
        LocalDate currentDate = LocalDate.now();

        // Validating to rewrite textfield if not empty
        if (textAge.getText() != "") {
            textAge.setText("");
            //Outputting the date
            int ResultYear = Period.between(selectedDate, currentDate).getYears();
            textAge.setText("" + ResultYear);
        } else if (textAge.getText() == "") {
            textAge.setText("");
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser birthDate;
    private javax.swing.JButton btnAddRec;
    private javax.swing.JButton btnCancel;
    private rojerusan.RSComboMetro comboGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_patientID;
    public static javax.swing.JLabel lblDate;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextArea textAreaPrescription;
    private javax.swing.JTextArea textAreaRemarks;
    private javax.swing.JTextField textFatherAge;
    private javax.swing.JTextField textFatherFName;
    private javax.swing.JTextField textFatherLName;
    private javax.swing.JTextField textFatherNumber;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textMotherAge;
    private javax.swing.JTextField textMotherFName;
    private javax.swing.JTextField textMotherLName;
    private javax.swing.JTextField textMotherNumber;
    private javax.swing.JTextField textPhoneNo;
    // End of variables declaration//GEN-END:variables
}
